markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginator: paginate
paginate: 5
paginate_path: "blog/page:num"

# presonal config
domain: blog.hipoplar.me
title: Hipoplar
description: iOS, Ruby, Java Web, Linux, PHP, Javascript...
author: Vincent Yang
email: soda1015@foxmail.com
github: soda1015

config:
  js_dir:
  img_dir:
  css_dir:
