permalink: :year/:month/:title.html
url: 
lsi: false
safe: true
auto: false 

paginator: paginate
paginate: 5
paginate_path: "blog/page:num"

# presonal config
domain: hipopulus.cn
title: Hi Populus
description:
author: Vince.Y
email: soda1015@foxmail.com
github: hipopulus

config:
  js_dir:
  img_dir:
  css_dir:
