markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: blog.hipoplar.me
title: Poplar's Blog
description: iOS, Ruby, Java Web, Linux, reading...
author: Vincent Yang
email: soda1015@foxmail.com
github: soda1015

config:
  js_dir:
  img_dir:
  css_dir:
